stages:
  - build
  - test

build:
  stage: build
  services:
    - docker:dind
  image: docker:latest
  script:
    - docker-compose up --build
    - sleep 5

test:
  stage: test
  image: python:3.9
  script:
    - pip install requests beautifulsoup4
    - python3 ../task4/health_check.py

